logging:
#  file: logs/insertMaker.log
#  config: classpath:logback-spring.xml
  level:
    root: info
    org.springframework.web: info
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace


spring:
  jpa:
#    defer-datasource-initialization : true
    # ddl-autoNoneを設定しないとファイルからのデータ読み込みが無視される？
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:postgresql://localhost:5432/todo}
    username: ${DATABASE_USER:sample}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
#      mode: always
      enabled: true
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  main:
    allow-circular-references: true


